### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by asciian** [fossamagna/gas-webpack-plugin#136]
Hi. Thank you for great plugin! With your plugin I tried to make a library but I got this error when I push the script produced by gas-webpack-plugin with @google/clasp. 

For more detail you can see: 

```
Push failed. Errors:
Syntax error: Missing name after . operator. line: 151 file: index
Files to push were:
└─ dist/appsscript.json
└─ dist/index.js
```

Whole code is [here](https://github.com/asciian/cheeriogs). Please don't forget change scriptId in clasp to try to push.

Thank you.

**Comment by asciian** [comment]
Error code is here.
```js
var parse = __webpack_require__(4),
    defaultOptions = __webpack_require__(93).default,
    flattenOptions = __webpack_require__(93).flatten,
    isHtml = __webpack_require__(145).isHtml,
    _ = {
  extend: __webpack_require__(146),
  bind: __webpack_require__(150),
  forEach: __webpack_require__(195),
  defaults: __webpack_require__(202)
};
```

it's happend around `default` keyword in line 2. Perhaps GAS omitted `default` keyword.

**Comment by fossamagna** [comment]
SyntaxError is happened because of `default` is reserved word in GAS. 
You can avoid this error by accessing to an object's properties by using the bracket notation.

[babel-prsest-gas](https://github.com/fossamagna/babel-preset-gas) is babel preset to transpile from dot notation to bracket notation.
Please try to use babel-preset-gas.

**Comment by asciian** [comment]
I got it. I'll use the preset which is your advice. Thank you so much.

**Comment by asciian** [comment]
Unfortunately, babel converts only source codes excepts utilities. Now we have

```js
/*
 * Utilities generated by webpack...
 */

/*
 * Source code converted by babel...
 */

/*
 * ...Source code converted by babel
 */

/*
 * ...Utilities generated by webpack
 */
```

And Webpack generates the code which not be able to run in GAS.
Now we have two choices
- Using [es3-compatible-webpack-plugin]()
- After webpack builds, re-converting to es3 code with your plugin babel-preset-gas.

I want you to add the feature which es3-compatible-webpack-plugin has into your plugin to became truly the plugin for GAS.
Could you do that?

**Comment by asciian** [comment]
Now I solved by using babel-webpack-plugin instead of babel-loader.

**Comment by p6l-richard** [comment]
> Now I solved by using babel-webpack-plugin instead of babel-loader.

Hi @fgborges facing the same issue here -- would you be so kind to outline how you set up the babel-webpack-plugin?

I tried the following in my `webpack.config.js` but it throws the same error.
```
const BabelPlugin = require('babel-webpack-plugin');
```
...
```
plugins: [
  new BabelPlugin({ presets: ['gas'] }),
]

```

**Comment by jonathanstokes** [comment]
For @p6l-richard and others who find there way here... I came close to solving this using Babel, but ended up rolling back.

What really solved it was adding `"runtimeVersion": "V8"` to my `appsscript.json` manifest. Using the V8 engine (available since 2020-feb-05) didn't require the Babel transpiling (it didn't mind the `.default` syntax), so everything just worked.
