### ISSUE TITLE
Cannot read property 'getChunkModules' of undefined

### ISSUE THREAD

**Issue by alexblack** [fossamagna/gas-webpack-plugin#562]
I'm trying out the latest version 2.0.1 and unfortunately my webpack build is failing with it:

```
 ERROR in chunk main [entry]
    code.js
    Cannot read property 'getChunkModules' of undefined
```

It works fine with 1.2.2 it seems.   Any suggestions? Thanks!!

**Comment by enuchi** [comment]
Having the same issue as above with trying to use 2.0.1. The build works with 1.2.2 but none of the globals are exposed. I can see the functions being copied over into the webpack output file, but doesn't look like they are available in the global scope, since when I open the Google Apps Script editor it says no functions found.

By the way, thanks for your great work on this repo! -- have been using for years on https://github.com/enuchi/React-Google-Apps-Script

<img width="760" alt="gas" src="https://user-images.githubusercontent.com/31550519/120751118-77af7e00-c4d5-11eb-9989-345aaf2a8015.png">

**Comment by fossamagna** [comment]
@alexblack @enuchi Thank you.
What webpack version you use ?
gas-webpack-plugin@2.x.x is only support webpack 5. If you use webpack 4, please use gas-webpack-plugin@1.x.x.


> By the way, thanks for your great work on this repo! -- have been using for years on https://github.com/enuchi/React-Google-Apps-Script

I am really honored to hear that.

**Comment by alexblack** [comment]
Hi @fossamagna thanks for getting back to me on this.  Yes I was using webpack v4, sorry about that. Ok I will close this then.
